# Generated by Django 5.2.5 on 2025-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_cart_quantity_alter_order_delivery_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
