# Generated by Django 5.2.7 on 2025-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/dcxbs1lon/image/upload/v1755066155/default_profile.jpg', upload_to='images'),
        ),
    ]
